project:
  type: website
  output-dir: docs

website:
  title: BigPicture
  favicon: favicon.ico
  description: >
    A central repository of digital pathology slides from biomedical research projects to boost the development of artificial intelligence
  image: images/bp-logo.png
  page-footer:
    background: light
    left:
      - text: Hosted by NBIS and Uppsala University
    center: 
      - about/terms-of-use.qmd
      - about/privacy-notice.qmd
    right:
      - href: about/contact-us.qmd
  cookie-consent:
    type: express

  page-navigation: true
  navbar:
    title: false
    logo: images/bp-logo-one-line.png
    logo-alt: BigPicture
    background: light
    collapse-below: lg
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: submission/index.qmd
        text: Submission
  
  sidebar:
    - id: submit
      title: Submission
      style: floating
      collapse-level: 2
      align: left
      contents:
        - submission/index.qmd
        - section: Preparation guide
          contents:
            - submission/preparing-data.qmd

        - section: Submission guide
          contents:
            - submission/uploading-data.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    code-copy: true
    code-overflow: wrap
    toc: true
