---
pagetitle: BigPicture Maintenance Window
sidebar: false
toc: false
aliases:
  - maintenence_window.html
include-in-header:
    - text: |
        <meta name="google-site-verification" content="zCbRdYQIJhqk-MBVfUpr3GXL0AMrCZmCz0jnPcctmwU" />
---

# Maintenance Window

## 2025-03-03

On Monday 3rd of March, we will begin maintenance work on the BigPicuture infrastructure. During this time, disruptions to the availability of SDA services may be observed. We will do our best to keep the downtime to a minimum. A notification will be sent out when work is finished. Maintenance work will mainly consist of updating running services to their latest stable version.

While this update is mostly for updating our internal services to improve submission automation there is on change to services that are relevant to BigPicture users are listed below.

 * The repository's public key is now available as a base64 encoded string form the login pages info endpoint https://login.bp.nbis.se/info

## 2024-09-30

On Monday 30th of September, we will begin maintenance work on the BigPicuture infrastructure. During this time, disruptions to the availability of SDA services may be observed. We will do our best to keep the downtime to a minimum. A notification will be sent out when work is finished. Maintenance work will mainly consist of updating running services to their latest stable version.

Changes to services that are relevant to BigPicture users and/or the helpdesk team are listed below.

### SDA Download

New service for accessing datasets in the BigPicture repository. Now it’s not necessary to use the work-around with sending emails and public keys but instead once you’ve gotten access to a dataset in REMS you can access it directly via sda-cli (version 0.1.2).

The download service currently supports downloading both decrypted files or files encrypted with your public key directly to your environment.

### SDA CLI

It is now possible to provide the the authentication token in the environment instead of having it in the configuration file (version 0.1.3).

### SDA Login

Correct branding for authentication services in the login portal
