---
pagetitle: BigPicture Changelog 2025-03-03
sidebar: false
toc: false
aliases:
  - maintenence_window.html
---

# Detailed Changelog 2025-03-03

## Auth
 * Update OIDC library by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/946
 * Server public key as a base64 encoded string by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/947
 * Make the TTL of  the resigned token configurable by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/944
 * Enable configurable TTL for resigned OIDC token by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1109

## Download
 * Feat: configurable allow uncrypted download by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/887
 * Update the metadata from the sda-download API by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/923
 * Ignore trailing slashes in ISS and JKU URLs by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/949
 * Health head request for download by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/978
 * Update readme for the download api by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/967
 * Add grpc healthcheck by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/988
 * Upgrade ristretto to v1.0.0 by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1081

## Admin API
 * Admin API Service by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/955, https://github.com/neicnordic/sensitive-data-archive/pull/956, https://github.com/neicnordic/sensitive-data-archive/pull/983
 * Add some basic sanity checking when creating a dataset by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1111
 * Expand key hash actions by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1107
 * Add c4gh hash keys by @kostas-kou in https://github.com/neicnordic/sensitive-data-archive/pull/1084
 * Add a RBAC solution by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1115
 * Add sanity checks when releasing a dataset.  by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1080

## S3Inbox
 * Support http head requests to s3inbox's healthcheck by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/977
 * Tls for the health endpoint by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/993
 * Run healthchecks in main process by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1025
 * Disallow reserved characters by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/965

## sda-admin CLI
 * Sda-admin cli  by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/1026
 * Add key hash handling by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1108
 * Add user to create dataset command by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1114

## SDA
 * Add timestamp to MQ messages by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/943
 * Import LICENSE from previous repository by @viklund in https://github.com/neicnordic/sensitive-data-archive/pull/1039
 * Update CONTRIBUTING to be on par with the NeIC handbook by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/1006
 * Update api.md by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/1016
 * Use go 1.23 by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1046
 * Resolve deprecation in AWS library by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/894
 * Add checks for integer overflows by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/1001


## Github actions
 * Remove obsolete doc update workflow by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/969

## Database
 * Add key hash to the files table by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/994
 * Grant select permission to role "download" on dataset_event_log table by @Parisa68 in https://github.com/neicnordic/sensitive-data-archive/pull/989
 * Restore lega_in and lega_out password setting by @Parisa68 in https://github.com/neicnordic/sensitive-data-archive/pull/916
 * Add missing entry from dbschema_version by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1110

## SFTP-inbox
 * Change sftp-inbox path to sda-sftp-inbox by @Parisa68 in https://github.com/neicnordic/sensitive-data-archive/pull/1015

## SDA-DOA
 * Merge sda-doa by @Parisa68 in https://github.com/neicnordic/sensitive-data-archive/pull/876

## Ingest
 * Store keyhash for ingested files by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1126
 * Fix: prevent endless logging from finalize by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1082

## Charts
 * Fix sync and sync-api deployments by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/867
 * Add charts install instructions readme by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/971
 * Feature/admin api charts by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/972
 * Add nginx-affinity label to ingress templates in the SDA-SVC chart. by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/904
 * Add more review suggestions for chart README by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/984
