---
pagetitle: BigPicture Changelog 2025-10-06
sidebar: false
toc: false
---

# Detailed Changelog 2025-10-06

## Admin-API

 * Return stable ID as part of the file info response. by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1506
 * Download re-encrypted file from the inbox by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/1627
 * Optimize db queries for /users and /files by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/1792
 * Reduce verbose logging from GIN by @zeidlitz in https://github.com/neicnordic/sensitive-data-archive/pull/1799

## Auth

 * Serve both raw (for download) and resigned (for upload) tokens by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/1362
 * Fix blank page on failed ega login by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1460

## Finalize

 * Allow starting without backup enabled by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1879

## Download

 * Configurable s3 endpoint for download by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/1163
* Tidier gin logs by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1266
* Fix/latest linter suggestions by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/1790

## Ingest
 * Support multiple C4GH keys by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/1197
 * Wait for delays from s3 by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1483
 * Refactor main work loop by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1526
 * Ensure cryp4gh keys are loaded on startup. by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1663
 * Register configured C4GH keys on startup by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1794

## S3Inbox

 * Persist fileID over changes of the service instance by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/1357
 * Send remove message on overwrite by @MalinAhlberg in https://github.com/neicnordic/sensitive-data-archive/pull/1543
 * Store uploaded file size in db by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1571

## Verify

 * Support multiple private keys by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/1235
 * More robust against getting stuck in broker message loops by @aaperis in https://github.com/neicnordic/sensitive-data-archive/pull/1600

## Common

 * Update Go to version 1.24 by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1429
 * Add test step to append files to a dataset. by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1507 
 * Update constraint to also include the submission user by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1594
 * Adjust log levels by @zeidlitz in https://github.com/neicnordic/sensitive-data-archive/pull/1764 
 * Remove string concatenations from SQL queries. by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1797
 * Ensure all switches have a default case by @jbygdell in https://github.com/neicnordic/sensitive-data-archive/pull/1818 
 * Include file-id in loginfo  by @nanjiangshu in https://github.com/neicnordic/sensitive-data-archive/pull/1857
