---
title: Metadata overview
---

## Why is metadata important?

Data submitted to FEGA Sweden must be described with proper metadata.
Well described datasets are easier for other researchers to find and
reuse.

It is good practice to have a plan for collecting and keeping the
metadata already at an early stage in a research project. Here are some
examples of what can happen if you don't have a plan for your metadata:

-   You fail to understand your data because critical metadata got lost
    when a colleague moved to a new job and forgot to hand over the
    metadata to you.
-   You need to spend more time collecting the metadata because you
    forgot where to get it from.
-   You cannot deposit the data into a public repository because you
    forgot where you put the metadata.
-   The publication of your scientific results is delayed because some
    metadata is missing (the journal may for example demand you to
    deposit data in a repository that requires metadata that you don't
    have access to).
-   Another researcher cannot use your data because you forgot to
    collect some critical metadata (e.g. about how an experiment was
    done or the conditions for using the data).

## The metadata model

The metadata in FEGA Sweden is divided into eight major categories (see
figure below). Submitted data files are connected to either the "Runs"
or the "Analysis" category. You can prepare most of the metadata before
you start working on the actual submission. Well-prepared metadata will
facilitate the future processing of your submission.

[![The metadata model in FEGA
Sweden.](/images/fega-metadata-model.png){fig-alt="Metadata model for sequence submissions"
fig-align="center" width="100%"}](/images/fega-metadata-model.png)

## Some general advice on metadata management

-   Keep the metadata in a single location. Consider storing the
    metadata close to your data files (but in a separate folder). Make
    sure that files are backed up regularly so that you don't loose
    important information.
-   Keep your metadata files organised. Decide on one file naming
    convention and stick with that. Also make sure to document your
    metadata files. A simple
    [README](https://en.wikipedia.org/wiki/README) file that describes
    the files is normally sufficient.
-   Clarify responsibilities in your team when it comes to collecting
    and keeping the metadata.

## Where should I start?

We know that it can take time to prepare the metadata. To help you on
your way, we have put together information about the metadata categories
that we think will be the most valuable to prepare early:

-   [Sample metadata](sample-metadata.qmd)
-   [Experiment metadata](experiment-metadata.qmd)
-   [Analysis metadata](analysis-metadata.qmd)
-   [Data Access Committee (DAC) metadata](dac-metadata.qmd)
-   [Policy documentation](policy-documentation.qmd)
