---
title: Policy documentation
---

The policy documentation specifies the terms and conditions for using a
dataset. This category of metadata is critical for enabling secondary
use of data. It will also help researchers in deciding whether they
should request access to a dataset or not.

### Data Access Agreement (DAA)

The Data Access Agreement (DAA) is a contract made between one or more
data users and the DAC. The agreement text should be drafted by the DAC
and includes, but is not limited to, details of data use, publication
embargoes and storage. Completion of a DAA by the applicant/s should
form part of the application process to the DAC. Your institution may
offer a standard text to use.

### Data use conditions

In addition to the DAA, you are also required to specify under which
conditions a researcher may use your data with [Data Use Ontology (DUO)
codes](https://ega-archive.org/data-use-conditions). The codes will make
it easier for other researchers to know if and how they can use your
data. Select maximum one primary DUO code and any number of secondary
codes.
