---
title: Sample metadata
---

## Metadata fields

The table below shows the fields that can be specified for each sample.
An asterisk indicates the fields that are required in submissions to
FEGA Sweden.

::: callout-important
This is only for the public sample metadata. Make sure that it is not
possible to identify individual people from information that you share
publicly. Any sensitive information should be submitted as data.
:::

| Field name      | Description                                                                                            |
|------------------------|-----------------------------------------------|
| Alias\*         | The submitter's designated name for the sample. The name must be unique within the submission account. |
| Title           | A short informative description of the sample                                                          |
| Description     | A longer description of sample and how it differs from other samples                                   |
| Subject ID\*    | An identifier for subject or donor of the sample                                                       |
| BioSampleID     | BioSampleID if relevant                                                                                |
| Case or control | "case", "control", "both" or "NA"                                                                      |
| Gender\*        | "female", "male" or "unknown"                                                                          |
| Organism part   | Part of organism                                                                                       |
| Cell line       | Cell line                                                                                              |
| Region          | Geographic region                                                                                      |
| Phenotype\*     | Phenotype or disease state relevant for using the data                                                 |

FEGA Sweden recommends using the [Experimental Factor Ontology
Database](http://bioportal.bioontology.org/ontologies/EFO?p=classes) for
describing your sample phenotypes. Whenever applicable, we also
recommend using appropriate [INSDC terms for missing
values](https://ena-docs.readthedocs.io/en/latest/submit/samples/missing-values.html).

## Sample metadata templates

Templates for sample metadata are available in the following formats:

| File format                 | Download                                                                                          | Description                                                            |
|-------------------|-------------------------------|-----------------------|
| Text CSV                    | <a href="templates/sample-metadata.csv" download="sample-metadata.csv">sample-metadata.csv</a>    | Plain text template without validation                                 |
| ODF Spreadsheet             | <a href="templates/sample-metadata.ods" download="sample-metadata.ods">sample-metadata.ods</a>    | [LibreOffice](https://www.libreoffice.org) spreadsheet with validation |
| Office Open XML Spreadsheet | <a href="templates/sample-metadata.xlsx" download="sample-metadata.xlsx">sample-metadata.xlsx</a> | Microsoft Excel spreadsheet with validation                            |
