---
title: About BigPicture Sweden
---

## Introduction

BigPicture Sweden is an archive for storing and sharing digital pathology slides resulting from biomedical research projects. As a national node of the
BigPicture (https://bigpicture.eu/),
we enable researchers to store their data in Sweden in a way that meets the
requirements of the General Data Protection Regulation (GDPR). Any data 
submitted to the archive is subject to controlled access, which means that 
access to the data only will be granted after a formal application procedure. 
Using BigPicture Sweden for storing and sharing data is free of charge for academic users.

## Our mission


## The organisations behind BigPicture Sweden

BigPicture Sweden is hosted by the [National Bioinformatics Infrastructure
Sweden (NBIS)](https://nbis.se), which legally is part of [Uppsala
University](https://uu.se). NBIS forms the bioinformatics platform at
[SciLifeLab](https://scilifelab.se) and constitutes the Swedish node of
the European organisation [ELIXIR](https://elixir-europe.org).

## Partners and initiatives

