---
title: Terms of use
---

<!-- TODO: Update version number and date for Terms of Use -->

<!-- Version: x (yyyy-mm-dd) -->

Draft version

## General

1. BigPicture Sweden provides freely available online services, databases and 
software for storing and sharing digital pathology slides resulting from
biomedical research projects. Where we present scientific data generated by others we impose no additional restriction on the use of the contributed data than those provided by the data owner.

2. BigPicture Sweden expects attribution (e.g. in publications, services or products) for any of its online services, databases or software in accordance with good scientific practice. The expected attribution will be indicated on the appropriate web page.

3. Any feedback provided to BigPicture Sweden on its online services will be treated as non-confidential unless the individual or organisation providing the 
feedback states otherwise.

4. BigPicture Sweden is not liable to you or third parties claiming through you, for any loss or damage.

5. All scientific data will be made available by a time and release mechanism 
consistent with the data type (e.g. human data where access needs to be 
reviewed by a Data Access Committee, pre-publication embargoed for a specific 
time period).

6. Personal data held by BigPicture Sweden will only be released in exceptional circumstances when required by law or judicial or regulatory order. BigPicture Sweden may make information about the total volume of usage of particular software or data available to the public and third party organisations who supply the software or databases without details of any individual's use.

7. We reserve the right to update these Terms of Use at any time. When 
alterations are inevitable, we will attempt to give reasonable notice of any 
changes by placing a notice on our website, but you may wish to check each time 
you use the website. The date of the most recent revision will appear on this, 
the 'BigPicture Sweden Terms of Use' page. If you do not agree to these changes, please do not continue to use our online services. We will also make available an archived copy of the previous Terms of Use for comparison.

8. Any questions or comments concerning these terms of use can be addressed to:

   Uppsala University  
   ICM – Department of Cell and Molecular Biology  
   NBIS  
   Box 596  
   SE-751 24 Uppsala


## Online services

1. Users of BigPicture-Sweden's online services agree not to attempt to use any BigPicture Sweden computers, files or networks apart from through the service interfaces provided.

2. BigPicture Sweden's websites uses cookies to record information about your online preferences that allow us to personalise your experience of the website. You can control your use of cookies from your web browser, but if you choose not to accept cookies from BigPicture Sweden's website, you will not be able to take full advantage of all of the website’s features. Read more about how we handle cookies in [NBIS' privacy policy](https://nbis.se/about/privacy.html)

3. BigPicture Sweden will make all reasonable effort to maintain continuity of these online services and provide adequate warning of any changes or discontinuities. However, BigPicture Sweden accepts no responsibility for the consequences of any temporary or permanent discontinuity in service.

4. Any attempt to use BigPicture Sweden's online services to a level that prevents, or looks likely to prevent, BigPicture Sweden providing services to others, will result in the use being blocked. BigPicture Sweden will attempt to contact the user to discuss their needs and how (and if) these can be met from other sources.

5. If you post or send offensive, inappropriate or objectionable content 
anywhere on or to our websites or otherwise engage in any disruptive behaviour 
on any of our services, we may use your personal information from our security 
logs to stop such behaviour. Where we reasonably believe that you are or may be 
in breach of any applicable laws we may use your personal information to inform 
relevant third parties about the content and your behaviour.

6. Software that can be run from the BigPicture Sweden webpages may be used by any individual for any purpose unless specific exceptions are stated on the web 
page. Any software from BigPicture Sweden made available for download through our web pages (either directly or from third party repositories) will have its own individual license agreement.

7. BigPicture Sweden has implemented appropriate technical and organisational 
measures to ensure a level of security which we deem appropriate, taking into 
account the categories of data we collect and the way we process it.

8. BigPicture Sweden does not accept responsibility for the consequences of any 
breach of the confidentiality of BigPicture Sweden site by third parties.


## Data services

1. When you contribute scientific data to BigPicture Sweden through our website or other submission tools this information will be released at a time and in a 
manner consistent with the scientific data and we may store it permanently.

2. BigPicture Sweden itself places no additional restrictions on the use or 
redistribution of the data available via its online services other than those 
provided by the original data owners.

3. BigPicture Sweden does not guarantee the accuracy of any provided data, generated database, software or online service nor the suitability of databases, software and online services for any purpose.

4. The original data may be subject to rights claimed by third parties, 
including but not limited to, patent, copyright, or other intellectual property 
rights. For Human data consented for biomedical research, these rights may be 
formalised in Data Access Agreements. It is the responsibility of users of the 
BigPicture Sweden services to ensure that their exploitation of the data does not infringe any of the rights of such third parties.


## Privacy

1. BigPicture Sweden is operated by National Bioinformatics Infrastructure Sweden (NBIS). Your rights in relation to personal data are detailed in 
[NBIS' internal privacy policy](https://nbis.se/about/privacy.html).

2. Since NBIS is legally part of Uppsala University, BigPicture Sweden is also bound by the university's [data protection policy](https://www.uu.se/en/about-uu/data-protection-policy/).
 
