---
title: "Data availability statement"
editor: visual
---

Many scientific journals request authors to include a *data availability
statement* (also called *data accessibility statement*) in submitted
articles. We advise you to check if your target journal has any specific
recommendations regarding the format.

If you need inspiration, this is what the statement could look like:

> The sequence data presented in this paper contains sensitive
> information that cannot be shared openly. The authors\' intention is
> however to share the data under controlled access via FEGA Sweden once
> this repository becomes operational. FEGA Sweden is a national node of
> the Federated European Genome-phenome Archive (FEGA), which is hosted
> by the National Bioinformatics Infrastructure Sweden (NBIS) at
> SciLifeLab. The datasets will then be findable through the European
> Genome-phenome Archive web portal
> ([https://ega-archive.org](https://ega-archive.org/)). Information
> about the datasets included in this study is available at SciLifeLab
> Data Repository, DOI {insert DOI}.

::: callout-important
Until FEGA Sweden is taken into production it is advisable to create a
*metadata record* describing the data. The last sentence in the example
text above includes a reference to such a metadata record. You can read
more about metadata records in the [SciLifeLab Research Data Management
Guidelines](https://data-guidelines.scilifelab.se/topics/sharing-human-data/#if-data-cannot-be-deposited-in-a-repository).
:::
