---
title: Ethical approval
---

## Introduction

If you plan to do research in Sweden that involves processing of
sensitive personal data, you must have an ethical approval from the
[Swedish Ethical Review Authority](https://etikprovningsmyndigheten.se/)
before you begin your research. An ethical approval may also be required
under other circumstances that involve research on humans or on human
biological material. You can enable others to reuse your data by
specifying in the application how the data is going to be shared. The
application that you send in to the Swedish Ethical Review Authority has
to be in Swedish.

## Informed consent

Depending on what kind of research you are doing, you may be required to
collect consent agreements from the research participants. This means
that the participants---before they consent to participate---must be
informed about the purpose of the research, as well as about any risks
and benefits involved in their participation. The information that you
plan to give to the participants should be attached to your ethical
review application. [The Ethical Review
Act](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-2003460-om-etikprovning-av-forskning-som_sfs-2003-460)
specifies when consent agreements are required.

When you prepare the information for the participants, it might be a
good to think of the following:

-   Express clearly that the participant's personal data may be used in
    other research projects. Try to define the data reuse conditions by
    specifying a research purpose rather than by stating with whom the
    data can be shared. In particular, do not limit the data access to
    only researchers, since researchers sometimes need help from
    non-researchers (e.g. technical staff) with the data.
-   Consider which countries the data can be shared with. Can it be
    shared only within EU/EES? Or perhaps only within Sweden?
-   Personal data must normally be pseudonymised before it is shared.
    Don't forget to inform the participants about that. Data that is
    pseudonymised can only be used to identify individuals in
    combination with other data.

The Swedish Ethical Review Authority offers a template ("Stödmall för
forskningspersonsinformation") on its website for writing the
information that will be given to research participants. For your
convenience, we have prepared an example paragraph (see below) that you
can insert into the template (under the heading "Vad händer med mina
uppgifter?"). The text should make it possible for you to share your
data via FEGA Sweden.

> Personuppgifter kan komma att lämnas vidare till forskare och andra
> behöriga för efterföljande forskning inom eller utanför landet. Varje
> utlämning av data kommer då att prövas individuellt för att
> säkerställa att forskningen sker i enlighet med det här projektets
> etikgodkännande och att personuppgifterna kan hanteras säkert.
> Personuppgifter som lämnas vidare kommer att vara pseudonymiserade,
> vilket innebär att de endast kan kopplas till en fysisk identifierbar
> person med hjälp av kompletterande uppgifter. Överföring av
> personuppgifter till tredje land, dvs. ett land utanför EU/EES, eller
> en internationell organisation får endast ske om EU-kommissionen
> beslutat att mottagande land kan säkerställa en adekvat dataskyddsnivå
> eller om mottagaren av uppgifterna i ett tredje land tecknar ett avtal
> om åtkomst av data enligt EU-kommissionens specifikationer som
> garanterar adekvat dataskyddsnivå.

::: callout-note
Although we think that the text above would be appropriate to include in
information to research participants, we cannot guarantee that the
Swedish Ethical Review Authority will find it acceptable in an ethical
review application.
:::

## Renewing an ethical approval

If you already have an ethical approval but the application was written
without having data sharing via FEGA Sweden in mind, you may want to
apply for a renewal of the approval. Read more about renewal
applications on the website of the [Swedish Ethical Review
Authority](https://etikprovningsmyndigheten.se/).

## Learn more about ethical review

We have collected a few links where you can read more about ethical
review in Sweden.

-   [Swedish Ethical Review
    Authority](https://etikprovningsmyndigheten.se/) (in Swedish)
-   [Ethical
    review](https://snd.gu.se/en/manage-data/plan/ethical-review) -- by
    the Swedish National Data Service (SND)
-   [The Act concerning the Ethical Review of Research Involving Humans
    (2003:460)](https://www.riksdagen.se/sv/dokument-lagar/dokument/svensk-forfattningssamling/lag-2003460-om-etikprovning-av-forskning-som_sfs-2003-460)
    (in Swedish)
-   [CODEX rules and guidelines for
    research](https://codex.uu.se/?languageId=1) -- by Uppsala
    University
