---
title: Is FEGA Sweden the right archive?
---

Before you start working on a submission, you should ask yourself whether FEGA
Sweden is the right place for storing and sharing your data. This guide will
help you assess the suitability of FEGA Sweden to your data. If you need help
with the assessment, please write to the [FEGA Sweden Helpdesk](mailto:{{< var email.helpdesk >}}).


## Is my data of the right type?

FEGA Sweden aims to store the same kind of data as the [European Genome-phenome Archive 
(EGA)](https://ega-archive.org), which basically means any data resulting from
biomedical research projects. You can read more about data types and file 
formats on the EGA website (see for instance supported [file formats for sequence data](https://ega-archive.org/submission/sequence)).


## Does my data require controlled access?

Sensitive personal data can normally not be shared publicly due to legal and
ethical constraints. FEGA Sweden makes it possible to share sensitive personal
data under controlled access. This means that access to any submitted file will
be determined by a formal application procedure. If your data does not require
controlled access, you should consider submitting it to an alternative
repository, such as the [European Nucleotide Archive (ENA)](https://www.ebi.ac.uk/ena/browser/submit).


## Is my data from a Swedish research project?

FEGA Sweden is a national node of the 
[Federated EGA](https://ega-archive.org/about/projects-and-funders/federated-ega/)
that primarily hosts data from Swedish research projects. You are welcome to
contact us if you want to discuss strategies for sharing your data.


## Am I allowed to share the data via FEGA Sweden?

If you plan to make personally identifiable data accessible to others, there are
some special regulations that you have to be aware of. If the research is
carried out in Sweden, you must for example have an [ethical approval](ethical-approval.qmd).
You must also make sure that the data processing [comply with GDPR](complying-with-gdpr.qmd).
