---
title: Quick guide
---

This is an overview of the submission process. Please read through the steps
outlined below before you fill in the [submission request form](submission-request.qmd).
If you have questions or comments, please write to the [BigPicture Sweden Helpdesk](mailto:{{< var email.helpdesk >}}).


::: {.callout-note}
BigPicture Sweden is not yet operational. We are currently piloting the submission process with a few selected datasets. Our initial focus will be to support submission of sequence data and variants. Any changes to the status of the repository will be announced on the BigPicture Sweden website.
:::

::: {.grid}

::: {.g-col-4}
1. Create a submission request
:::
::: {.g-col-8}
If you consider BigPicture Sweden to be the right place for your data, please fill in the [submission request webform](submission-request.qmd).
The BigPicture Sweden Helpdesk will evaluate your request and get back to you 
regarding how to proceed.

:::

::: {.g-col-4}
2. Receive credentials for a submission account at EGA
:::
::: {.g-col-8}
Once your submission request has been accepted, BigPicture Sweden Helpdesk will request a submission account for you at EGA. Using the received credentials, you should be able to log in to the Submitter Portal.
:::

::: {.g-col-4}
3. Register Study, Sample, DAC and Policy
:::
::: {.g-col-8}
Use the Submitter Portal to register your Study, Samples, Data Access Committee
(DAC) and Policy (including a Data Access Agreement).
:::

::: {.g-col-4}
4. Upload data
:::
::: {.g-col-8}
For details, see our [upload instructions](uploading-data.qmd).
:::

::: {.g-col-4}
5. Register Experiments and Runs
:::
::: {.g-col-8}
Associate each data file with a registered sample and study by linking files
to samples in the Submitter Portal. Details of the experimental procedure you
followed must be provided.
:::

::: {.g-col-4}
6. Finish your submission
:::
::: {.g-col-8}
Group your runs/analysis into datasets and link them to your new or existing
Data Access Committee (DAC) and Data Access Agreement (DAA) using the 
Submitter Portal. Data requests are done at a dataset level, thus files within
a dataset must share release conditions.
:::

::: {.g-col-4}
7. Release the data
:::
::: {.g-col-8}
Instruct the BigPicture Sweden Helpdesk to release your study. All registered
studies are automatically placed on hold ('embargoed') until the named 
submission or Data Access Committee (DAC) contact instructs the BigPicture Sweden Helpdesk for the study to be released. 
:::

:::
