---
title: Data access overview
---

This page describes how you request access to datasets deposited in BigPicture Sweden. For any questions regarding data access, please write to the [BigPicture Sweden Helpdesk](mailto:{{< var email.helpdesk >}}).

Each dataset stored in BigPicture Sweden is affiliated with a Data Access Committee (DAC), which is the body responsible for all data access decisions.

::: {.grid}

::: {.g-col-4}
1. Identify dataset(s)
:::
::: {.g-col-8}
Identify the dataset(s) you want to request access for.
:::

::: {.g-col-4}
2. Request access
:::
::: {.g-col-8}
Identify the Data Access Committee (DAC) affiliated with the dataset(s) you
wish to request access for. Then, contact the DAC to start your data access
application. A Data Access Agreement (DAA) documenting the terms of access
and usage of the dataset needs to be negotiated between you and the DAC and
should be signed by both parts.
:::

::: {.g-col-4}
3. Receive download instructions
:::
::: {.g-col-8}
Once the DAC has accepted your data access request and an authorisation has been granted, you will recieve instructions from the BigPicture Sweden Helpdesk on how to access the data.
:::

::: {.g-col-4}
4. Download and decrypt files
:::
::: {.g-col-8}
Follow the [instructions](downloading-data.qmd) on how to download and 
decrypt files. Please note that you need to confirm successful download
and decryption to the Helpdesk.
:::

:::
