name: Publish to Github Pages

on:
  push:
    branches:
    - minimal-web

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
    - name: Install Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.2.313

    - name: Checkout files
      uses: actions/checkout@v3

    - name: Render
      uses: quarto-dev/quarto-actions/render@v2
      env:
        CAPTCHAKEY: ${{ vars.CAPTCHAKEY }}
        SKULD: ${{ vars.SKULD }}
      with:
        path: .
        to: html

    - name: Publish to Github Pages
      uses: quarto-dev/quarto-actions/publish@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target: gh-pages
        render: false

